services:
  db:
    image: postgres:14
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-passwd}
      POSTGRES_DB: db
      PGDATABASE: db
      PGPASSWORD: ${POSTGRES_PASSWORD:-passwd}
      PGUSER: ${POSTGRES_USER:-postgres}
    ports:
      - 127.0.0.1:${LOCAL_DB_PORT:-15432}:5432

  app:
    build: .
    # restart: always
    command: sh ./start_web.sh
    environment:
      APP_ENV: production
      ALCHEMICAL_DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-passwd}@db:5432/db
    depends_on:
      - db
    ports:
      - 127.0.0.1:${LOCAL_WEB_PORT:-8001}:8000

  api:
    build: .
    # restart: always
    command: sh ./start_api.sh
    environment:
      APP_ENV: production
      IS_API: true
      ALCHEMICAL_DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-passwd}@db:5432/db
    depends_on:
      - db
    ports:
      - 127.0.0.1:${LOCAL_API_PORT:-8002}:8000

  backup:
    image: simple2b/pg-backup:1.0
    restart: always
    volumes:
      - ./backup:/backup
    links:
      - db
    environment:
      APP_ENV: production
      SCHEDULE_DAY: ${SCHEDULE_DAY:-31}  # scheduler for every 31 days - never
      POSTGRES_DATABASE: db
      POSTGRES_HOST: db
      POSTGRES_USER: ${DATABASE_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-passwd}
      POSTGRES_EXTRA_OPTS: '--schema=public --blobs'
      DAYS_HISTORY: 7
      SCHEDULE_HOUR: 0
      SCHEDULE_MINUTE: 0
      SCHEDULE_SECOND: 0
      S3_REGION: ${S3_REGION:-**None**}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID:-**None**}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY:-**None**}
      S3_BUCKET: ${S3_BUCKET:-**None**}
      S3_PREFIX: ${S3_PREFIX:-**None**}
      AWS_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID:-**None**}
      AWS_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY:-**None**}
      AWS_DEFAULT_REGION: ${S3_REGION:-**None**}

volumes:
  db_data:
