services:
  db:
    image: postgres:14
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-passwd}
      POSTGRES_DB: db
      PGDATABASE: db
      PGPASSWORD: ${POSTGRES_PASSWORD:-passwd}
      PGUSER: ${POSTGRES_USER:-postgres}

  app:
    image: simple2b/kraftjar:0.1
    restart: always
    command: sh ./start_web.sh
    environment:
      APP_ENV: production
      ALCHEMICAL_DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-passwd}@db:5432/db
    env_file:
      - .env
    volumes:
      - ./credentials.json:/home/app/credentials.json
    depends_on:
      - db
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.kraftjar_portal.rule=Host(`www.kraftjar.net`, `kraftjar.net`)'
      - 'traefik.http.routers.kraftjar_portal.tls=true'
      - 'traefik.http.routers.kraftjar_portal.tls.certresolver=myresolver'

  api:
    image: simple2b/kraftjar:0.1
    restart: always
    command: sh ./start_api.sh
    environment:
      APP_ENV: production
      IS_API: 'true'
      ALCHEMICAL_DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-passwd}@db:5432/db
    env_file:
      - .env
    depends_on:
      - db
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.kraftjar_api.rule=Host(`api.kraftjar.net`)'
      - 'traefik.http.routers.kraftjar_api.tls=true'
      - 'traefik.http.routers.kraftjar_api.tls.certresolver=myresolver'

  backup:
    image: simple2b/pg-backup:1.0
    restart: unless-stopped
    links:
      - db
    environment:
      # scheduler for every 3 days
      APP_ENV: production
      SCHEDULE_DAY: ${SCHEDULE_DAY:-3}
      POSTGRES_DATABASE: db
      POSTGRES_HOST: db
      POSTGRES_USER: ${DATABASE_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}
      POSTGRES_EXTRA_OPTS: '--schema=public --blobs'
      DAYS_HISTORY: 7
      SCHEDULE_HOUR: 0
      SCHEDULE_MINUTE: 0
      SCHEDULE_SECOND: 0
      S3_REGION: ${S3_REGION:-**None**}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID:-**None**}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY:-**None**}
      S3_BUCKET: ${S3_BUCKET:-**None**}
      S3_PREFIX: ${S3_PREFIX:-**None**}
      AWS_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID:-**None**}
      AWS_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY:-**None**}
      AWS_DEFAULT_REGION: ${S3_REGION:-**None**}

volumes:
  db_data:
