"""empty message

Revision ID: 0eae751d0bf8
Revises: 18a7d53aa473
Create Date: 2024-10-17 15:11:05.234364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eae751d0bf8'
down_revision = '18a7d53aa473'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('content', sa.String(length=1024), nullable=False),
    sa.Column('fcm_id', sa.String(length=512), server_default='', nullable=False),
    sa.Column('n_type', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_push_notifications_created_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_push_notifications'))
    )
    op.create_table('notification_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_notification_devices_device_id_devices')),
    sa.ForeignKeyConstraint(['notification_id'], ['push_notifications.id'], name=op.f('fk_notification_devices_notification_id_push_notifications')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_devices'))
    )
    op.create_table('notification_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['push_notifications.id'], name=op.f('fk_notification_users_notification_id_push_notifications')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notification_users_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_users'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_users')
    op.drop_table('notification_devices')
    op.drop_table('push_notifications')
    # ### end Alembic commands ###
