"""add user avatar

Revision ID: 1024f3058b04
Revises: 600f5a66e36c
Create Date: 2024-10-24 11:37:21.254278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1024f3058b04'
down_revision = '600f5a66e36c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_users_avatar_id_files'), 'files', ['avatar_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_avatar_id_files'), type_='foreignkey')
        batch_op.drop_column('avatar_id')

    # ### end Alembic commands ###
