"""job_description_len

Revision ID: 12bb37c7d575
Revises: 5e1c08ca7d4a
Create Date: 2024-02-26 17:07:21.461612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12bb37c7d575'
down_revision = '5e1c08ca7d4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=1024),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=512),
               nullable=False)

    # ### end Alembic commands ###
