"""fields

Revision ID: 16801e766765
Revises: e7829ef80645
Create Date: 2024-01-24 17:02:00.058340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16801e766765'
down_revision = 'e7829ef80645'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name_en', sa.String(length=128), nullable=False),
    sa.Column('name_ua', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fields'))
    )
    op.create_table('field_services',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], name=op.f('fk_field_services_field_id_fields')),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_field_services_service_id_services')),
    sa.PrimaryKeyConstraint('service_id', 'field_id', name=op.f('pk_field_services'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('field_services')
    op.drop_table('fields')
    # ### end Alembic commands ###
