"""rates_fix

Revision ID: 2f241050826f
Revises: 6c4488b55141
Create Date: 2024-03-05 16:19:17.415072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f241050826f'
down_revision = '6c4488b55141'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receiver_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_rates_receives_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_rates_receiver_id_users'), 'users', ['receiver_id'], ['id'])
        batch_op.drop_column('receives_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receives_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_rates_receiver_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_rates_receives_id_users', 'users', ['receives_id'], ['id'])
        batch_op.drop_column('receiver_id')

    # ### end Alembic commands ###
