"""add_street_type_field

Revision ID: 30726392eac5
Revises: f33811c61603
Create Date: 2024-09-03 12:15:02.002963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30726392eac5'
down_revision = 'f33811c61603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('street_type_ua', sa.String(length=36), server_default='', nullable=False))
        batch_op.add_column(sa.Column('street_type_en', sa.String(length=36), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_column('street_type_en')
        batch_op.drop_column('street_type_ua')

    # ### end Alembic commands ###
