"""add User notification settings fields

Revision ID: 3f3137615f68
Revises: 45a3171a0f7d
Create Date: 2024-11-02 13:44:36.144733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f3137615f68'
down_revision = '45a3171a0f7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_notification_statuses_application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name_ua', sa.String(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_notification_statuses_application_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_notification_statuses_application'))
    )
    op.create_table('user_notification_statuses_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name_ua', sa.String(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_notification_statuses_job_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_notification_statuses_job'))
    )
    op.create_table('user_notification_types_application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name_ua', sa.String(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_notification_types_application_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_notification_types_application'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_change_status_job_flag', sa.Boolean(), server_default='true', nullable=False))
        batch_op.add_column(sa.Column('notification_change_status_application_flag', sa.Boolean(), server_default='true', nullable=False))
        batch_op.add_column(sa.Column('notification_change_type_application_flag', sa.Boolean(), server_default='true', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('notification_change_type_application_flag')
        batch_op.drop_column('notification_change_status_application_flag')
        batch_op.drop_column('notification_change_status_job_flag')

    op.drop_table('user_notification_types_application')
    op.drop_table('user_notification_statuses_job')
    op.drop_table('user_notification_statuses_application')
    # ### end Alembic commands ###
