"""favorite_jobs

Revision ID: 42e20253b857
Revises: 115cf9531d31
Create Date: 2024-10-10 09:38:33.788579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42e20253b857'
down_revision = '115cf9531d31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_favorite_jobs_job_id_jobs')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_favorite_jobs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_favorite_jobs'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_jobs')
    # ### end Alembic commands ###
