"""job_cancel

Revision ID: 45a3171a0f7d
Revises: 1985e3b6e921
Create Date: 2024-10-31 10:17:20.194743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45a3171a0f7d'
down_revision = '1985e3b6e921'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancel_request_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('canceled_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_jobs_canceled_by_users'), 'users', ['canceled_by'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_jobs_cancel_request_by_users'), 'users', ['cancel_request_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_jobs_cancel_request_by_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_jobs_canceled_by_users'), type_='foreignkey')
        batch_op.drop_column('canceled_by')
        batch_op.drop_column('cancel_request_by')

    # ### end Alembic commands ###
