"""add job_files

Revision ID: 550a53dee628
Revises: b014eebfc332
Create Date: 2024-09-15 23:04:46.050371

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '550a53dee628'
down_revision = 'b014eebfc332'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('original_name', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('key', sa.String(length=512), nullable=False))
        batch_op.add_column(sa.Column('title', sa.String(length=256), server_default='', nullable=False))
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.create_unique_constraint(batch_op.f('uq_files_key'), ['key'])
        batch_op.create_unique_constraint(batch_op.f('uq_files_name'), ['name'])
        batch_op.drop_column('url')
        batch_op.drop_column('filename')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('job_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_phone', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_users_phone', ['phone'])

    with op.batch_alter_table('job_files', schema=None) as batch_op:
        batch_op.drop_column('id')

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_files_name'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_files_key'), type_='unique')
        batch_op.alter_column('type',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('title')
        batch_op.drop_column('key')
        batch_op.drop_column('original_name')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
