"""job_location_id_none

Revision ID: 5e1c08ca7d4a
Revises: 6a8db5bf17ff
Create Date: 2024-02-26 16:42:14.087155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e1c08ca7d4a'
down_revision = '6a8db5bf17ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('location_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column("description", existing_type=sa.String(length=1024), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('location_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column("description", existing_type=sa.String(length=512), nullable=False)

    # ### end Alembic commands ###
