"""files_job

Revision ID: 600f5a66e36c
Revises: 3d7cc28716f4
Create Date: 2024-10-23 20:57:23.136046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '600f5a66e36c'
down_revision = '3d7cc28716f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_files_job_file_id_files')),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_files_job_job_id_jobs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_files_job'))
    )
    op.drop_table('job_files')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_files',
    sa.Column('file_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name='fk_job_files_file_id_files'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name='fk_job_files_job_id_jobs'),
    sa.PrimaryKeyConstraint('file_id', 'job_id', name='pk_job_files')
    )
    op.drop_table('files_job')
    # ### end Alembic commands ###
