"""rates

Revision ID: 6c4488b55141
Revises: b4e20fca65f1
Create Date: 2024-03-05 15:43:32.431990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c4488b55141'
down_revision = 'b4e20fca65f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rates', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
