"""empty message

Revision ID: 6f9d5e8b37f7
Revises: 70a9333776d8
Create Date: 2024-10-21 12:30:08.232976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f9d5e8b37f7'
down_revision = '70a9333776d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('push_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=36), server_default=sa.text('gen_random_uuid()'), nullable=False))
        batch_op.add_column(sa.Column('job_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_push_notifications_job_id_jobs'), 'jobs', ['job_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('push_notifications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_push_notifications_job_id_jobs'), type_='foreignkey')
        batch_op.drop_column('job_id')
        batch_op.drop_column('uuid')

    # ### end Alembic commands ###
