"""empty message

Revision ID: 70a9333776d8
Revises: cb7f01f0e7be
Create Date: 2024-10-20 12:10:20.513796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70a9333776d8'
down_revision = 'cb7f01f0e7be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform', sa.String(length=16), server_default='unknown', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_column('platform')

    # ### end Alembic commands ###
