"""auth_account_table

Revision ID: 841c8f177c1a
Revises: 1c3c96c0d6fd
Create Date: 2024-09-10 12:22:37.073390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '841c8f177c1a'
down_revision = '1c3c96c0d6fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('auth_type', sa.Enum('BASIC', 'GOOGLE', 'APPLE', 'DIIA', name='authtype'), nullable=False),
    sa.Column('oauth_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_accounts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_accounts')),
    sa.UniqueConstraint('email', 'auth_type', 'user_id', name='uq_email_auth_type_user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('apple_id')
        batch_op.drop_column('email')
        batch_op.drop_column('google_id')
        batch_op.drop_column('diia_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diia_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('google_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('apple_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False))

    op.drop_table('auth_accounts')
    # ### end Alembic commands ###
