"""auth_avatar

Revision ID: 96035366e1ed
Revises: 8401d4d9a8a4
Create Date: 2024-11-18 10:00:43.368214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96035366e1ed'
down_revision = '8401d4d9a8a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_accounts', schema=None) as batch_op:
        batch_op.drop_column('avatar_url')

    # ### end Alembic commands ###
