"""education_table

Revision ID: 96af476a5597
Revises: fc8d9e984d5d
Create Date: 2024-11-15 08:19:10.725485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96af476a5597'
down_revision = 'fc8d9e984d5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('educations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('institution', sa.String(length=128), nullable=False),
    sa.Column('degree', sa.String(length=128), nullable=True),
    sa.Column('specialization', sa.String(length=128), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_educations_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_educations'))
    )
    op.create_table('files_education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('education_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['education_id'], ['educations.id'], name=op.f('fk_files_education_education_id_educations')),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_files_education_file_id_files')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_files_education'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files_education')
    op.drop_table('educations')
    # ### end Alembic commands ###
