"""add job_rates

Revision ID: 9e47b1e91002
Revises: ee6b79b79b0d
Create Date: 2024-10-21 10:13:12.406895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e47b1e91002'
down_revision = 'ee6b79b79b0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rate_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_rates_job_id_jobs')),
    sa.ForeignKeyConstraint(['rate_id'], ['rates.id'], name=op.f('fk_job_rates_rate_id_rates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_rates'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_rates')
    # ### end Alembic commands ###
