"""job model -> dates, negotiable, volunteer

Revision ID: b014eebfc332
Revises: 841c8f177c1a
Create Date: 2024-09-13 17:12:18.203454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b014eebfc332'
down_revision = '841c8f177c1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_negotiable', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('is_volunteer', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.drop_column('time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
        batch_op.drop_column('is_volunteer')
        batch_op.drop_column('is_negotiable')
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###
