"""saved_jobs

Revision ID: b4e20fca65f1
Revises: 12bb37c7d575
Create Date: 2024-02-28 18:07:55.325069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4e20fca65f1'
down_revision = '12bb37c7d575'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_jobs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_saved_jobs_job_id_jobs')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_saved_jobs_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'job_id', name=op.f('pk_saved_jobs'))
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.Float(), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)
        batch_op.alter_column('address_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('address_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
        batch_op.drop_column('cost')

    op.drop_table('saved_jobs')
    # ### end Alembic commands ###
