"""change User notification settings fields

Revision ID: baafb51100e3
Revises: 72af3520e64b
Create Date: 2024-11-05 17:12:18.907574

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'baafb51100e3'
down_revision = '72af3520e64b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_notification_statuses_application')
    op.drop_table('user_notification_types_application')
    op.drop_table('user_notification_statuses_job')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_pending_job_status', sa.Boolean(), server_default='true', nullable=False))
        batch_op.add_column(sa.Column('is_approved_job_status', sa.Boolean(), server_default='true', nullable=False))
        batch_op.add_column(sa.Column('is_in_progress_job_status', sa.Boolean(), server_default='true', nullable=False))
        batch_op.add_column(sa.Column('is_on_confirmation_job_status', sa.Boolean(), server_default='true', nullable=False))
        batch_op.add_column(sa.Column('is_payment_confirmed_job_status', sa.Boolean(), server_default='true', nullable=False))
        batch_op.add_column(sa.Column('is_completed_job_status', sa.Boolean(), server_default='true', nullable=False))
        batch_op.add_column(sa.Column('is_canceled_job_status', sa.Boolean(), server_default='true', nullable=False))
        batch_op.add_column(sa.Column('is_pending_aplication_status', sa.Boolean(), server_default='true', nullable=False))
        batch_op.add_column(sa.Column('is_accepted_aplication_status', sa.Boolean(), server_default='true', nullable=False))
        batch_op.add_column(sa.Column('is_rejected_aplication_status', sa.Boolean(), server_default='true', nullable=False))
        batch_op.add_column(sa.Column('is_invite_application_type', sa.Boolean(), server_default='true', nullable=False))
        batch_op.add_column(sa.Column('is_apply_application_type', sa.Boolean(), server_default='true', nullable=False))
        batch_op.drop_column('notification_change_type_application_flag')
        batch_op.drop_column('notification_change_status_job_flag')
        batch_op.drop_column('notification_change_status_application_flag')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_change_status_application_flag', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('notification_change_status_job_flag', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('notification_change_type_application_flag', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
        batch_op.drop_column('is_apply_application_type')
        batch_op.drop_column('is_invite_application_type')
        batch_op.drop_column('is_rejected_aplication_status')
        batch_op.drop_column('is_accepted_aplication_status')
        batch_op.drop_column('is_pending_aplication_status')
        batch_op.drop_column('is_canceled_job_status')
        batch_op.drop_column('is_completed_job_status')
        batch_op.drop_column('is_payment_confirmed_job_status')
        batch_op.drop_column('is_on_confirmation_job_status')
        batch_op.drop_column('is_in_progress_job_status')
        batch_op.drop_column('is_approved_job_status')
        batch_op.drop_column('is_pending_job_status')

    op.create_table('user_notification_statuses_job',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name_ua', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name_en', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_notification_statuses_job_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_user_notification_statuses_job')
    )
    op.create_table('user_notification_types_application',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name_ua', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name_en', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_notification_types_application_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_user_notification_types_application')
    )
    op.create_table('user_notification_statuses_application',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name_ua', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name_en', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_notification_statuses_application_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_user_notification_statuses_application')
    )
    # ### end Alembic commands ###
