"""rate

Revision ID: c2f1dfe8fe11
Revises: 70b5ff7a1255
Create Date: 2024-03-07 10:54:11.704397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2f1dfe8fe11'
down_revision = '70b5ff7a1255'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('average_rate', sa.Float(), nullable=True))

    op.execute("UPDATE users SET average_rate = 1")
    batch_op.alter_column('average_rate', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('average_rate')

    # ### end Alembic commands ###
