"""empty message

Revision ID: cb7f01f0e7be
Revises: ece32226fb7e
Create Date: 2024-10-18 12:44:10.622138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb7f01f0e7be'
down_revision = 'ece32226fb7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('push_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta_data', sa.String(length=1024), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('push_notifications', schema=None) as batch_op:
        batch_op.drop_column('meta_data')

    # ### end Alembic commands ###
