"""add_meest_api_fields

Revision ID: f33811c61603
Revises: c2f1dfe8fe11
Create Date: 2024-08-28 13:17:50.575648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f33811c61603'
down_revision = 'c2f1dfe8fe11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('street_id', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('city_id', sa.String(length=36), nullable=False))

    with op.batch_alter_table('rayons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('district_id', sa.String(length=36), nullable=False))

    with op.batch_alter_table('settlements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('district_id', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('city_id', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('kt', sa.String(length=36), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('average_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('average_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)

    with op.batch_alter_table('settlements', schema=None) as batch_op:
        batch_op.drop_column('kt')
        batch_op.drop_column('city_id')
        batch_op.drop_column('district_id')

    with op.batch_alter_table('rayons', schema=None) as batch_op:
        batch_op.drop_column('district_id')

    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_column('city_id')
        batch_op.drop_column('street_id')

    # ### end Alembic commands ###
