"""password_strength

Revision ID: fc8d9e984d5d
Revises: baafb51100e3
Create Date: 2024-11-13 09:13:37.615883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc8d9e984d5d'
down_revision = 'baafb51100e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_strength', sa.String(length=16), server_default='weak', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_strength')

    # ### end Alembic commands ###
